backend:
  name: test-repo

media_folder: public/images
public_folder: /images

collections:
  - name: settings
    label: Portfolio Settings
    files:
      - file: src/data/settings.json
        label: Settings
        name: settings
        format: json
        fields:
          - label: Portfolio Name
            name: portfolioName
            widget: string
          - label: Portfolio Manager
            name: portfolioManager
            widget: string
          - label: Last Updated
            name: lastUpdated
            widget: datetime
            format: YYYY-MM-DD HH:mm
          - label: Total Value
            name: totalValue
            widget: number
          - label: Benchmark Index
            name: benchmark
            widget: string
          - label: YTD Performance %
            name: ytdPerformance
            widget: number
